using System.Data;
using System.Diagnostics;
using System.Diagnostics.Metrics;
using System.Net.Sockets;
using System.Threading.Channels;
using Confluent.Kafka;
using FalconFX.Protos;
using FalconFX.ServiceDefaults;
using FalconFX.TradeProcessor.Data;
using Microsoft.EntityFrameworkCore;
using Npgsql;
using NpgsqlTypes;
using StackExchange.Redis;

namespace FalconFX.TradeProcessor;

public readonly record struct TradeWorkItem(TradeRecord Record, ConsumeResult<Ignore, byte[]> ConsumeResult);

public sealed class Worker : BackgroundService
{
    private const int BatchSize = 10_000;
    private const string Topic = "trades";

    private static readonly Meter Meter = new("FalconFX.TradeProcessor");

    private static readonly Counter<long> TradesPersisted = Meter.CreateCounter<long>(
        "tradeprocessor.trades.persisted", "trades", "Total trades persisted to PostgreSQL");

    private static readonly Counter<long> TickerUpdates = Meter.CreateCounter<long>(
        "tradeprocessor.ticker.updates", "updates", "Total ticker updates published to Redis");

    private readonly IConfiguration _config;
    private readonly IConsumer<Ignore, byte[]> _consumer;

    private readonly ILogger<Worker> _logger;
    private readonly Channel<ConsumeResult<Ignore, byte[]>> _offsetStoreChannel;
    private readonly IConnectionMultiplexer _redis;
    private readonly Channel<TradeExecuted> _redisChannel;
    private readonly IServiceProvider _serviceProvider;

    private readonly Channel<TradeWorkItem> _tradeChannel;

    public Worker(
        ILogger<Worker> logger,
        IServiceProvider serviceProvider,
        IConsumer<Ignore, byte[]> consumer,
        IConnectionMultiplexer redis,
        IConfiguration config)
    {
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _serviceProvider = serviceProvider ?? throw new ArgumentNullException(nameof(serviceProvider));
        _consumer = consumer ?? throw new ArgumentNullException(nameof(consumer));
        _redis = redis ?? throw new ArgumentNullException(nameof(redis));
        _config = config ?? throw new ArgumentNullException(nameof(config));

        _tradeChannel = Channel.CreateBounded<TradeWorkItem>(new BoundedChannelOptions(500_000)
        {
            FullMode = BoundedChannelFullMode.Wait,
            SingleReader = true,
            SingleWriter = true
        });

        _redisChannel = Channel.CreateBounded<TradeExecuted>(new BoundedChannelOptions(10_000)
        {
            FullMode = BoundedChannelFullMode.DropOldest,
            SingleReader = true,
            SingleWriter = true
        });

        _offsetStoreChannel = Channel.CreateUnbounded<ConsumeResult<Ignore, byte[]>>(new UnboundedChannelOptions
        {
            SingleReader = true,
            SingleWriter = true
        });
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _logger.LogTradeProcessorStarting();

        await KafkaUtils.WaitForBrokerReady(_config, _logger, stoppingToken).ConfigureAwait(false);
        await KafkaUtils.EnsureTopicExistsAsync(_config, _logger, Topic).ConfigureAwait(false);

        await Task.Delay(2000, stoppingToken).ConfigureAwait(false);

        // CREATE TABLE IF NOT EXISTS
        using (var scope = _serviceProvider.CreateScope())
        {
            var db = scope.ServiceProvider.GetRequiredService<TradeDbContext>();
            try
            {
                await db.Database.ExecuteSqlRawAsync("""
                                                         CREATE TABLE IF NOT EXISTS "Trades" (
                                                             "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                             "MakerOrderId" bigint NOT NULL,
                                                             "TakerOrderId" bigint NOT NULL,
                                                             "Price" bigint NOT NULL,
                                                             "Quantity" bigint NOT NULL,
                                                             "Symbol" text NOT NULL,
                                                             "Timestamp" bigint NOT NULL,
                                                             "InsertedAt" timestamp with time zone NOT NULL
                                                         );
                                                         CREATE INDEX IF NOT EXISTS "IX_Trades_Symbol_Timestamp" ON "Trades" ("Symbol", "Timestamp");
                                                     """, stoppingToken).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                _logger.LogWarning("Database table check warning: {Message}", ex.Message);
            }
        }

        _consumer.Subscribe(Topic);
        _logger.LogKafkaConsumerSubscribed(Topic);

        var consumeTask = Task.Factory.StartNew(
            () => ConsumeKafkaLoopAsync(stoppingToken),
            stoppingToken, TaskCreationOptions.LongRunning, TaskScheduler.Default).Unwrap();

        var dbTask = Task.Factory.StartNew(
            () => DbBatchWriterLoopAsync(stoppingToken),
            stoppingToken, TaskCreationOptions.LongRunning, TaskScheduler.Default).Unwrap();

        var redisTask = Task.Factory.StartNew(
            () => RedisPublisherLoopAsync(stoppingToken),
            stoppingToken, TaskCreationOptions.LongRunning, TaskScheduler.Default).Unwrap();

        await Task.WhenAll(consumeTask, dbTask, redisTask).ConfigureAwait(false);
    }

    private async Task ConsumeKafkaLoopAsync(CancellationToken token)
    {
        try
        {
            while (!token.IsCancellationRequested)
            {
                while (_offsetStoreChannel.Reader.TryRead(out var resultToStore))
                    try
                    {
                        _consumer.StoreOffset(resultToStore);
                    }
                    catch (Exception ex)
                    {
                        _logger.LogKafkaCommitError(ex.Message);
                    }

                try
                {
                    var result = _consumer.Consume(TimeSpan.FromMilliseconds(10));
                    if (result?.Message?.Value is null)
                        continue;

                    while (result?.Message?.Value is not null && !token.IsCancellationRequested)
                    {
                        var trade = TradeExecuted.Parser.ParseFrom(result.Message.Value);
                        var record = TradeRecord.FromProto(trade);
                        var workItem = new TradeWorkItem(record, result);

                        if (!_tradeChannel.Writer.TryWrite(workItem))
                            await _tradeChannel.Writer.WriteAsync(workItem, token).ConfigureAwait(false);

                        _redisChannel.Writer.TryWrite(trade);

                        result = _consumer.Consume(TimeSpan.Zero);
                    }
                }
                catch (ConsumeException ex)
                {
                    _logger.LogKafkaConsumeWarning(ex.Error.Reason);
                    await Task.Delay(10, token).ConfigureAwait(false);
                }
            }
        }
        catch (OperationCanceledException)
        {
        }
        finally
        {
            _tradeChannel.Writer.TryComplete();
            _redisChannel.Writer.TryComplete();
            _offsetStoreChannel.Writer.TryComplete();
            try
            {
                _consumer.Close();
            }
            catch
            {
            }
        }
    }

    private async Task DbBatchWriterLoopAsync(CancellationToken token)
    {
        var batch = new List<TradeWorkItem>(BatchSize);

        using var scope = _serviceProvider.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<TradeDbContext>();
        var conn = (NpgsqlConnection)db.Database.GetDbConnection();

        try
        {
            while (!token.IsCancellationRequested)
            {
                if (batch.Count == 0)
                    if (!await _tradeChannel.Reader.WaitToReadAsync(token).ConfigureAwait(false))
                        break;

                while (batch.Count < BatchSize && _tradeChannel.Reader.TryRead(out var item)) batch.Add(item);

                if (batch.Count > 0)
                {
                    var success = false;
                    var retryDelay = TimeSpan.FromSeconds(1);
                    const int maxRetries = 5;
                    var attempt = 0;

                    while (!success && attempt < maxRetries && !token.IsCancellationRequested)
                        try
                        {
                            if (conn.State != ConnectionState.Open)
                                await conn.OpenAsync(token).ConfigureAwait(false);

                            var sw = Stopwatch.StartNew();

                            await using (var writer = await conn.BeginBinaryImportAsync(
                                             """
                                             COPY "Trades" ("MakerOrderId", "TakerOrderId", "Price", "Quantity", "Symbol", "Timestamp", "InsertedAt")
                                             FROM STDIN (FORMAT BINARY)
                                             """, token).ConfigureAwait(false))
                            {
                                foreach (var item in batch)
                                {
                                    var r = item.Record;
                                    var utcInsertedAt = r.InsertedAt.Kind == DateTimeKind.Utc
                                        ? r.InsertedAt
                                        : DateTime.SpecifyKind(r.InsertedAt, DateTimeKind.Utc);

                                    await writer.StartRowAsync(token).ConfigureAwait(false);
                                    await writer.WriteAsync(r.MakerOrderId, NpgsqlDbType.Bigint, token)
                                        .ConfigureAwait(false);
                                    await writer.WriteAsync(r.TakerOrderId, NpgsqlDbType.Bigint, token)
                                        .ConfigureAwait(false);
                                    await writer.WriteAsync(r.Price, NpgsqlDbType.Bigint, token).ConfigureAwait(false);
                                    await writer.WriteAsync(r.Quantity, NpgsqlDbType.Bigint, token)
                                        .ConfigureAwait(false);
                                    await writer.WriteAsync(r.Symbol, NpgsqlDbType.Text, token).ConfigureAwait(false);
                                    await writer.WriteAsync(r.Timestamp, NpgsqlDbType.Bigint, token)
                                        .ConfigureAwait(false);
                                    await writer.WriteAsync(utcInsertedAt, NpgsqlDbType.TimestampTz, token)
                                        .ConfigureAwait(false);
                                }

                                await writer.CompleteAsync(token).ConfigureAwait(false);
                            }

                            sw.Stop();

                            var lastItem = batch[^1];
                            _offsetStoreChannel.Writer.TryWrite(lastItem.ConsumeResult);

                            TradesPersisted.Add(batch.Count);
                            _logger.LogBatchSaved(batch.Count, sw.ElapsedMilliseconds);

                            success = true;
                            batch.Clear();
                        }
                        catch (Exception ex) when (ex is SocketException or NpgsqlException)
                        {
                            attempt++;
                            _logger.LogWarning(
                                "Database connection failed. Attempt {Attempt}/{Max}. Retrying in {Delay}ms... Error: {Msg}",
                                attempt, maxRetries, retryDelay.TotalMilliseconds, ex.Message);

                            if (conn.State != ConnectionState.Closed)
                                await conn.CloseAsync().ConfigureAwait(false);

                            await Task.Delay(retryDelay, token).ConfigureAwait(false);
                            retryDelay =
                                TimeSpan.FromMilliseconds(retryDelay.TotalMilliseconds * 2); // Exponential Backoff
                        }

                    if (!success)
                    {
                        _logger.LogCritical(
                            "Failed to persist trades batch after max retries. Potential data loss prevention active.");
                        throw new InvalidOperationException("Postgres persistence failed permanently.");
                    }
                }
            }
        }
        catch (OperationCanceledException)
        {
        }
    }

    private async Task RedisPublisherLoopAsync(CancellationToken token)
    {
        var redisDb = _redis.GetDatabase();

        try
        {
            while (await _redisChannel.Reader.WaitToReadAsync(token).ConfigureAwait(false))
            {
                TradeExecuted? latestTrade = null;

                while (_redisChannel.Reader.TryRead(out var trade)) latestTrade = trade;

                if (latestTrade is not null)
                    try
                    {
                        var payload = FormatRedisPayload(latestTrade.Symbol, latestTrade.Price);

                        await redisDb.StringSetAsync($"ticker:{latestTrade.Symbol}", latestTrade.Price)
                            .ConfigureAwait(false);
                        await redisDb.PublishAsync(RedisChannel.Literal("market_updates"), payload)
                            .ConfigureAwait(false);

                        TickerUpdates.Add(1);
                    }
                    catch
                    {
                    }

                await Task.Delay(10, token).ConfigureAwait(false);
            }
        }
        catch (OperationCanceledException)
        {
        }
    }

    private static string FormatRedisPayload(string symbol, long price)
    {
        Span<char> buffer = stackalloc char[symbol.Length + 1 + 20];
        symbol.AsSpan().CopyTo(buffer);
        buffer[symbol.Length] = ':';
        price.TryFormat(buffer[(symbol.Length + 1)..], out var written);
        return new string(buffer[..(symbol.Length + 1 + written)]);
    }
}

internal static partial class TradeProcessorLogExtensions
{
    [LoggerMessage(EventId = 301, Level = LogLevel.Information, Message = "TradeProcessor Worker starting...")]
    public static partial void LogTradeProcessorStarting(this ILogger logger);

    [LoggerMessage(EventId = 302, Level = LogLevel.Information,
        Message = "Trade Processor Started. Listening to topic '{Topic}'...")]
    public static partial void LogKafkaConsumerSubscribed(this ILogger logger, string topic);

    [LoggerMessage(EventId = 303, Level = LogLevel.Warning, Message = "Kafka Consume Warning: {Reason}. Retrying...")]
    public static partial void LogKafkaConsumeWarning(this ILogger logger, string reason);

    [LoggerMessage(EventId = 304, Level = LogLevel.Warning, Message = "Failed to commit Kafka offsets: {Message}")]
    public static partial void LogKafkaCommitError(this ILogger logger, string message);

    [LoggerMessage(EventId = 305, Level = LogLevel.Information,
        Message = "Saved {Count:N0} trades to database in {Time}ms")]
    public static partial void LogBatchSaved(this ILogger logger, int count, long time);
}